# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8316d4ad39afc112a30bb0a018f5923f2ba3d2db79066696e40c2b83e032af15df879e8a0f6e0b9fbfd30a6e9801a7e64a015224ec53e9e383ed980cdc0df07

test:
  secret_key_base: a4761e9223c06c524ec339eb15c88641c2f7983dd0420bd6a5b2698ed7bf2d4d149a096032401fe005a22407cfe6b95073a3b9b5ea2fd49a37465cf71e8a3542

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
